[project]
name = "inspiratron"
version = "0.0.1"
description = "An agentic bot to provide a daily quote based on current affairs"
authors = [
    {name = "Walden Bodtker", email = "waldnzwrld@gmail.com"}
    ]
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
  "huggingface-hub",
  "torch",
  "transformers"
]
project.optional-dependencies = []

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-cov (>=7.0.0,<8.0.0)",
    "pytest-mock (>=3.15.1,<4.0.0)",
    "black (>=25.12.0,<26.0.0)",
    "isort (>=7.0.0,<8.0.0)"
]

[tool.pytest.ini_options]
pythonpath = ["."]
